# This file was generated by GoReleaser. DO NOT EDIT.
cask "ripple" do
  version "0.3.1"

  on_macos do
    on_intel do
      sha256 "dffec18e4a758b2048e64ff8e4f0e04a8d80d36af659632357e0f05027f1ce59"
      url "https://github.com/urechandro/ripple/releases/download/v#{version}/ripple_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "ba59a904d6243772f5450563cff264f99b856001249cc63131fd08962350d485"
      url "https://github.com/urechandro/ripple/releases/download/v#{version}/ripple_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "cb1a70ddbb14bb42f9fb5e48dae107fbec17b5e7bf4ea118eb003dac19c6b043"
      url "https://github.com/urechandro/ripple/releases/download/v#{version}/ripple_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "6b04132ff43ede0ec46f6b47860b697dc8f3c9d154085a94d2d01762c1781523"
      url "https://github.com/urechandro/ripple/releases/download/v#{version}/ripple_Linux_arm64.tar.gz"
    end
  end

  name "ripple"
  desc "Watch Go file changes and run only the tests affected by your edit"
  homepage "https://github.com/urechandro/ripple"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ripple"

  # No zap stanza required

  postflight do
    system "xattr", "-d", "com.apple.quarantine", "#{staged_path}/ripple"
  end

end
