# This file was generated by GoReleaser. DO NOT EDIT.
cask "ripple" do
  version "0.5.0"

  on_macos do
    on_intel do
      sha256 "49e6b3bb5d98788ff1f6b1dee6c260dfdeb053dc7213210837bd9b386aba1e2d"
      url "https://github.com/urechandro/ripple/releases/download/v#{version}/ripple_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "4597495a866d6ffbac6c61e0d8bfcf4f9ac88d093174a868cb4734dfc248f419"
      url "https://github.com/urechandro/ripple/releases/download/v#{version}/ripple_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "4091cf1aff811e7b79453f88dffdfcc4eaf09268444dbc284312d5008f79fa25"
      url "https://github.com/urechandro/ripple/releases/download/v#{version}/ripple_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "1a5d0e7cc9cffb89eb72ef59535c96665d812902f523809aad4f5dbcd37523e0"
      url "https://github.com/urechandro/ripple/releases/download/v#{version}/ripple_Linux_arm64.tar.gz"
    end
  end

  name "ripple"
  desc "Watch Go file changes and run only the tests affected by your edit"
  homepage "https://github.com/urechandro/ripple"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ripple"

  # No zap stanza required

  postflight do
    system "xattr", "-d", "com.apple.quarantine", "#{staged_path}/ripple"
  end

end
