# This file was generated by GoReleaser. DO NOT EDIT.
cask "ripple" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "1a5f17d30efe44d36a8440b31f75bf0d053a33b247dff284eed0f0889092615e"
      url "https://github.com/urechandro/ripple/releases/download/v#{version}/ripple_Darwin_x86_64.tar.gz"
    end
    on_arm do
      sha256 "595ea4bba842065f709920fb0b89b77d52ae57d69ea8dd7299d83343e9193be7"
      url "https://github.com/urechandro/ripple/releases/download/v#{version}/ripple_Darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "48dd84a2ca2b6fcf19f5e8022c13c40346525c4b662f753f3f9b14c96517f188"
      url "https://github.com/urechandro/ripple/releases/download/v#{version}/ripple_Linux_x86_64.tar.gz"
    end
    on_arm do
      sha256 "02748963fd950bba43a869efc548af553c74d6e64ce67307a367ac14a961f706"
      url "https://github.com/urechandro/ripple/releases/download/v#{version}/ripple_Linux_arm64.tar.gz"
    end
  end

  name "ripple"
  desc "Watch Go file changes and run only the tests affected by your edit"
  homepage "https://github.com/urechandro/ripple"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "ripple"

  # No zap stanza required

end
